// Gumroad Connector Definition

import { ConnectorDefinition } from '../../shared';

export const GUMROAD_CONNECTOR: ConnectorDefinition = {
  name: 'gumroad',
  display_name: 'Gumroad',
  category: 'ecommerce',
  description: 'Digital product sales platform for creators and entrepreneurs',
  auth_type: 'bearer_token',
  auth_fields: [
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
      placeholder: 'Enter your Gumroad access token',
      description: 'Get your access token from Gumroad Settings > Advanced > Application Form',
      helpUrl: 'https://help.gumroad.com/article/280-gumroad-api',
      helpText: 'How to get an access token',
      order: 0,
    },
  ],
  endpoints: {
    base_url: 'https://api.gumroad.com/v2',
    products: '/products',
    sales: '/sales',
    subscribers: '/subscribers',
    resource_subscriptions: '/resource_subscriptions',
  },
  webhook_support: true,
  rate_limits: {
    requests_per_second: 10,
    requests_per_minute: 600,
  },
  sandbox_available: false,
  verified: false,
  supported_actions: [
    {
      id: 'get_product',
      name: 'Get Product',
      description: 'Retrieve a single product by ID',
      category: 'Products',
      icon: 'package',
      verified: false,
      inputSchema: {
        productId: {
          type: 'string',
          label: 'Product ID',
          description: 'The unique identifier of the product',
          required: true,
          placeholder: 'product_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        product: {
          type: 'object',
          description: 'Product details',
        },
      },
    },
    {
      id: 'list_products',
      name: 'List Products',
      description: 'Retrieve all products for the authenticated user',
      category: 'Products',
      icon: 'package',
      verified: false,
      inputSchema: {},
      outputSchema: {
        products: {
          type: 'array',
          description: 'Array of product objects',
        },
      },
    },
    {
      id: 'delete_product',
      name: 'Delete Product',
      description: 'Delete a product permanently',
      category: 'Products',
      icon: 'trash',
      verified: false,
      inputSchema: {
        productId: {
          type: 'string',
          label: 'Product ID',
          description: 'The unique identifier of the product to delete',
          required: true,
          placeholder: 'product_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        success: {
          type: 'boolean',
          description: 'Whether the deletion was successful',
        },
      },
    },
    {
      id: 'enable_product',
      name: 'Enable Product',
      description: 'Enable a product for sale',
      category: 'Products',
      icon: 'check-circle',
      verified: false,
      inputSchema: {
        productId: {
          type: 'string',
          label: 'Product ID',
          description: 'The unique identifier of the product to enable',
          required: true,
          placeholder: 'product_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        product: {
          type: 'object',
          description: 'Updated product details',
        },
      },
    },
    {
      id: 'disable_product',
      name: 'Disable Product',
      description: 'Disable a product from being sold',
      category: 'Products',
      icon: 'x-circle',
      verified: false,
      inputSchema: {
        productId: {
          type: 'string',
          label: 'Product ID',
          description: 'The unique identifier of the product to disable',
          required: true,
          placeholder: 'product_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        product: {
          type: 'object',
          description: 'Updated product details',
        },
      },
    },
    {
      id: 'get_sale',
      name: 'Get Sale',
      description: 'Retrieve details of a specific sale',
      category: 'Sales',
      icon: 'dollar-sign',
      verified: false,
      inputSchema: {
        saleId: {
          type: 'string',
          label: 'Sale ID',
          description: 'The unique identifier of the sale',
          required: true,
          placeholder: 'sale_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        sale: {
          type: 'object',
          description: 'Sale details including customer and product information',
        },
      },
    },
    {
      id: 'list_sales',
      name: 'List Sales',
      description: 'Retrieve all sales for the authenticated user',
      category: 'Sales',
      icon: 'dollar-sign',
      verified: false,
      inputSchema: {
        after: {
          type: 'string',
          label: 'After Date',
          description: 'Only return sales after this date (ISO 8601 format)',
          required: false,
          placeholder: '2024-01-01T00:00:00Z',
          order: 1,
          aiControlled: false,
        },
        before: {
          type: 'string',
          label: 'Before Date',
          description: 'Only return sales before this date (ISO 8601 format)',
          required: false,
          placeholder: '2024-12-31T23:59:59Z',
          order: 2,
          aiControlled: false,
        },
        page: {
          type: 'number',
          label: 'Page',
          description: 'Page number for pagination',
          required: false,
          default: 1,
          order: 3,
          aiControlled: false,
        },
      },
      outputSchema: {
        sales: {
          type: 'array',
          description: 'Array of sale objects',
        },
        next_page_url: {
          type: 'string',
          description: 'URL for the next page of results',
        },
      },
    },
    {
      id: 'refund_sale',
      name: 'Refund Sale',
      description: 'Refund a sale to the customer',
      category: 'Sales',
      icon: 'rotate-ccw',
      verified: false,
      inputSchema: {
        saleId: {
          type: 'string',
          label: 'Sale ID',
          description: 'The unique identifier of the sale to refund',
          required: true,
          placeholder: 'sale_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        success: {
          type: 'boolean',
          description: 'Whether the refund was successful',
        },
      },
    },
    {
      id: 'get_subscriber',
      name: 'Get Subscriber',
      description: 'Retrieve details of a specific subscriber',
      category: 'Subscriptions',
      icon: 'users',
      verified: false,
      inputSchema: {
        subscriberId: {
          type: 'string',
          label: 'Subscriber ID',
          description: 'The unique identifier of the subscriber',
          required: true,
          placeholder: 'subscriber_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        subscriber: {
          type: 'object',
          description: 'Subscriber details including subscription information',
        },
      },
    },
    {
      id: 'list_subscribers',
      name: 'List Subscribers',
      description: 'Retrieve all subscribers for a specific product',
      category: 'Subscriptions',
      icon: 'users',
      verified: false,
      inputSchema: {
        productId: {
          type: 'string',
          label: 'Product ID',
          description: 'The product ID to filter subscribers',
          required: true,
          placeholder: 'product_id',
          order: 1,
          aiControlled: false,
        },
        email: {
          type: 'string',
          label: 'Email',
          description: 'Filter by subscriber email',
          required: false,
          placeholder: 'user@example.com',
          order: 2,
          aiControlled: false,
        },
      },
      outputSchema: {
        subscribers: {
          type: 'array',
          description: 'Array of subscriber objects',
        },
      },
    },
    {
      id: 'create_webhook',
      name: 'Create Webhook',
      description: 'Create a webhook subscription for specific events',
      category: 'Webhooks',
      icon: 'webhook',
      verified: false,
      inputSchema: {
        url: {
          type: 'string',
          label: 'Webhook URL',
          description: 'The URL to send webhook notifications',
          required: true,
          placeholder: 'https://your-domain.com/webhook',
          order: 1,
          aiControlled: false,
        },
        events: {
          type: 'array',
          label: 'Events',
          description: 'Array of event types to subscribe to',
          required: true,
          itemSchema: {
            type: 'select',
            options: [
              { label: 'Sale', value: 'sale' },
              { label: 'Refund', value: 'refund' },
              { label: 'Dispute', value: 'dispute' },
              { label: 'Dispute Won', value: 'dispute_won' },
              { label: 'Cancellation', value: 'cancellation' },
            ],
          },
          order: 2,
          aiControlled: false,
        },
      },
      outputSchema: {
        webhook: {
          type: 'object',
          description: 'Created webhook details',
        },
      },
    },
    {
      id: 'list_webhooks',
      name: 'List Webhooks',
      description: 'List all webhook subscriptions',
      category: 'Webhooks',
      icon: 'webhook',
      verified: false,
      inputSchema: {},
      outputSchema: {
        webhooks: {
          type: 'array',
          description: 'Array of webhook subscription objects',
        },
      },
    },
    {
      id: 'delete_webhook',
      name: 'Delete Webhook',
      description: 'Delete a webhook subscription',
      category: 'Webhooks',
      icon: 'trash',
      verified: false,
      inputSchema: {
        webhookId: {
          type: 'string',
          label: 'Webhook ID',
          description: 'The unique identifier of the webhook to delete',
          required: true,
          placeholder: 'webhook_id',
          order: 1,
          aiControlled: false,
        },
      },
      outputSchema: {
        success: {
          type: 'boolean',
          description: 'Whether the deletion was successful',
        },
      },
    },
  ],
  supported_triggers: [
    {
      id: 'sale',
      name: 'New Sale',
      description: 'Triggers when a new sale is made',
      eventType: 'sale',
      icon: 'shopping-cart',
      verified: false,
      webhookRequired: true,
      outputSchema: {
        sale: {
          type: 'object',
          description: 'Sale details including customer, product, and payment information',
          properties: {
            id: { type: 'string', description: 'Unique sale identifier' },
            email: { type: 'string', description: 'Customer email' },
            product_id: { type: 'string', description: 'Product identifier' },
            product_name: { type: 'string', description: 'Product name' },
            price: { type: 'number', description: 'Sale price in cents' },
            currency: { type: 'string', description: 'Currency code' },
            quantity: { type: 'number', description: 'Quantity purchased' },
            sale_timestamp: { type: 'string', description: 'Timestamp of the sale' },
            license_key: { type: 'string', description: 'License key if applicable' },
          },
        },
      },
    },
    {
      id: 'refund',
      name: 'Sale Refunded',
      description: 'Triggers when a sale is refunded',
      eventType: 'refund',
      icon: 'rotate-ccw',
      verified: false,
      webhookRequired: true,
      outputSchema: {
        refund: {
          type: 'object',
          description: 'Refund details including sale ID and amount',
          properties: {
            id: { type: 'string', description: 'Unique refund identifier' },
            sale_id: { type: 'string', description: 'Original sale identifier' },
            email: { type: 'string', description: 'Customer email' },
            product_name: { type: 'string', description: 'Product name' },
            refunded_at: { type: 'string', description: 'Timestamp of the refund' },
          },
        },
      },
    },
    {
      id: 'dispute',
      name: 'Dispute Raised',
      description: 'Triggers when a dispute is raised against a sale',
      eventType: 'dispute',
      icon: 'alert-triangle',
      verified: false,
      webhookRequired: true,
      outputSchema: {
        dispute: {
          type: 'object',
          description: 'Dispute details including sale ID and reason',
          properties: {
            id: { type: 'string', description: 'Unique dispute identifier' },
            sale_id: { type: 'string', description: 'Original sale identifier' },
            email: { type: 'string', description: 'Customer email' },
            product_name: { type: 'string', description: 'Product name' },
            disputed_at: { type: 'string', description: 'Timestamp of the dispute' },
          },
        },
      },
    },
    {
      id: 'dispute_won',
      name: 'Dispute Won',
      description: 'Triggers when a dispute is won',
      eventType: 'dispute_won',
      icon: 'check-circle',
      verified: false,
      webhookRequired: true,
      outputSchema: {
        dispute: {
          type: 'object',
          description: 'Dispute resolution details',
          properties: {
            id: { type: 'string', description: 'Unique dispute identifier' },
            sale_id: { type: 'string', description: 'Original sale identifier' },
            email: { type: 'string', description: 'Customer email' },
            product_name: { type: 'string', description: 'Product name' },
            resolved_at: { type: 'string', description: 'Timestamp of the resolution' },
          },
        },
      },
    },
    {
      id: 'cancellation',
      name: 'Subscription Cancelled',
      description: 'Triggers when a subscription is cancelled',
      eventType: 'cancellation',
      icon: 'x-circle',
      verified: false,
      webhookRequired: true,
      outputSchema: {
        subscription: {
          type: 'object',
          description: 'Cancelled subscription details',
          properties: {
            id: { type: 'string', description: 'Unique subscription identifier' },
            product_id: { type: 'string', description: 'Product identifier' },
            product_name: { type: 'string', description: 'Product name' },
            user_email: { type: 'string', description: 'Subscriber email' },
            cancelled_at: { type: 'string', description: 'Timestamp of the cancellation' },
          },
        },
      },
    },
  ],
};
