import { ConnectorDefinition } from '../../shared';

export const GHOST_CONNECTOR: ConnectorDefinition = {
  name: 'ghost',
  display_name: 'Ghost',
  category: 'cms',
  description: 'Professional publishing platform for creating blogs and online publications',
  auth_type: 'custom',
  verified: false,

  auth_fields: [
    {
      key: 'source',
      label: 'API Source',
      type: 'select',
      required: true,
      options: [
        { label: 'Content API', value: 'contentApi' },
        { label: 'Admin API', value: 'adminApi' },
      ],
      default: 'contentApi',
      description: 'Choose between Content API (read-only) or Admin API (full access)',
    },
    {
      key: 'url',
      label: 'Ghost Site URL',
      type: 'string',
      required: true,
      placeholder: 'https://yourblog.ghost.io',
      description: 'Your Ghost site URL (e.g., https://example.com)',
    },
    {
      key: 'apiKey',
      label: 'API Key',
      type: 'password',
      required: true,
      placeholder: 'Enter your Ghost API key',
      description: 'Content API key or Admin API key depending on your selection',
      helpUrl: 'https://ghost.org/docs/admin-api/',
      helpText: 'How to get your API key',
    },
  ],

  endpoints: {
    base_url_content: '{url}/ghost/api/v3/content',
    base_url_admin: '{url}/ghost/api/v2/admin',
    posts: '/posts',
    post_by_id: '/posts/{id}',
    post_by_slug: '/posts/slug/{slug}',
  },

  webhook_support: false,

  rate_limits: {
    requests_per_second: 10,
  },

  supported_actions: [
    // Post Actions - Content API (Read-Only)
    {
      id: 'get_post',
      name: 'Get Post',
      description: 'Get a single post by ID or slug',
      category: 'Post',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/posts/{identifier}',
        method: 'GET',
        baseUrl: '{url}/ghost/api/{version}/content',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          identifier: 'identifier',
          fields: 'fields',
          formats: 'formats',
        },
      },
      inputSchema: {
        by: {
          type: 'select',
          required: true,
          label: 'Get By',
          default: 'id',
          options: [
            { label: 'ID', value: 'id' },
            { label: 'Slug', value: 'slug' },
          ],
          description: 'Get the post by ID or slug',
          aiControlled: false,
        },
        identifier: {
          type: 'string',
          required: true,
          label: 'Identifier',
          placeholder: 'post-id or post-slug',
          description: 'The ID or slug of the post to retrieve',
          aiControlled: false,
        },
        fields: {
          type: 'string',
          required: false,
          label: 'Fields',
          placeholder: 'title,slug,html',
          description: 'Comma-separated list of fields to return (e.g., title,url,html)',
          aiControlled: false,
        },
        formats: {
          type: 'array',
          required: false,
          label: 'Formats',
          description: 'Content formats to include',
          aiControlled: false,
        },
      },
      outputSchema: {
        post: {
          type: 'object',
          description: 'The post object',
        },
      },
    },
    {
      id: 'get_all_posts',
      name: 'Get All Posts',
      description: 'Get multiple posts with filtering and pagination',
      category: 'Post',
      icon: 'list',
      verified: false,
      api: {
        endpoint: '/posts',
        method: 'GET',
        baseUrl: '{url}/ghost/api/{version}/content',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          limit: 'limit',
          fields: 'fields',
          formats: 'formats',
          include: 'include',
        },
      },
      inputSchema: {
        returnAll: {
          type: 'boolean',
          required: false,
          label: 'Return All',
          default: false,
          description: 'Whether to return all results or only up to a limit',
          aiControlled: false,
        },
        limit: {
          type: 'number',
          required: false,
          label: 'Limit',
          default: 50,
          min: 1,
          max: 100,
          description: 'Maximum number of posts to return',
          aiControlled: false,
        },
        fields: {
          type: 'string',
          required: false,
          label: 'Fields',
          placeholder: 'title,slug,html',
          description: 'Comma-separated list of fields to return',
          aiControlled: false,
        },
        formats: {
          type: 'array',
          required: false,
          label: 'Formats',
          description: 'Content formats to include (html, plaintext)',
          aiControlled: false,
        },
        include: {
          type: 'array',
          required: false,
          label: 'Include',
          description: 'Related data to include (authors, tags)',
          aiControlled: false,
        },
      },
      outputSchema: {
        posts: {
          type: 'array',
          description: 'Array of post objects',
        },
      },
    },
    // Post Actions - Admin API (Full Access)
    {
      id: 'create_post',
      name: 'Create Post',
      description: 'Create a new post',
      category: 'Post',
      icon: 'plus',
      verified: false,
      api: {
        endpoint: '/posts',
        method: 'POST',
        baseUrl: '{url}/ghost/api/v2/admin',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          title: 'title',
          content: 'content',
          contentFormat: 'contentFormat',
          status: 'status',
          featured: 'featured',
          slug: 'slug',
          authors: 'authors',
          tags: 'tags',
          canonical_url: 'canonical_url',
          meta_title: 'meta_title',
          meta_description: 'meta_description',
          og_title: 'og_title',
          og_description: 'og_description',
          og_image: 'og_image',
          twitter_title: 'twitter_title',
          twitter_description: 'twitter_description',
          twitter_image: 'twitter_image',
          published_at: 'published_at',
          codeinjection_head: 'codeinjection_head',
          codeinjection_foot: 'codeinjection_foot',
        },
      },
      inputSchema: {
        title: {
          type: 'string',
          required: true,
          label: 'Title',
          placeholder: 'My Awesome Post',
          description: 'The post title',
          aiControlled: true,
          aiDescription: 'The title of the blog post. Should be engaging, descriptive, and SEO-friendly.',
        },
        contentFormat: {
          type: 'select',
          required: true,
          label: 'Content Format',
          default: 'html',
          options: [
            { label: 'HTML', value: 'html' },
            { label: 'Mobile Doc (JSON)', value: 'mobileDoc' },
            { label: 'Lexical (JSON)', value: 'lexical' },
          ],
          description: 'The format of the post content',
          aiControlled: false,
        },
        content: {
          type: 'string',
          required: true,
          label: 'Content',
          inputType: 'textarea',
          description: 'The post content (HTML or JSON depending on format)',
          aiControlled: true,
          aiDescription: 'The main body content of the blog post. Can include formatted text, headings, paragraphs, lists, and other HTML elements.',
        },
        status: {
          type: 'select',
          required: false,
          label: 'Status',
          default: 'draft',
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Published', value: 'published' },
            { label: 'Scheduled', value: 'scheduled' },
          ],
          description: 'Publication status',
          aiControlled: false,
        },
        slug: {
          type: 'string',
          required: false,
          label: 'Slug',
          placeholder: 'my-awesome-post',
          description: 'URL-friendly identifier for the post',
          aiControlled: false,
        },
        featured: {
          type: 'boolean',
          required: false,
          label: 'Featured',
          default: false,
          description: 'Mark post as featured',
          aiControlled: false,
        },
        authors: {
          type: 'array',
          required: false,
          label: 'Authors',
          description: 'Array of author IDs',
          aiControlled: false,
        },
        tags: {
          type: 'array',
          required: false,
          label: 'Tags',
          description: 'Array of tag names or IDs',
          aiControlled: false,
        },
        canonical_url: {
          type: 'string',
          required: false,
          label: 'Canonical URL',
          placeholder: 'https://example.com/original-post',
          description: 'The canonical URL for the post',
          aiControlled: false,
        },
        meta_title: {
          type: 'string',
          required: false,
          label: 'Meta Title',
          description: 'SEO meta title',
          aiControlled: true,
          aiDescription: 'The SEO meta title for search engine results. Should be concise and include relevant keywords.',
        },
        meta_description: {
          type: 'string',
          required: false,
          label: 'Meta Description',
          inputType: 'textarea',
          description: 'SEO meta description',
          aiControlled: true,
          aiDescription: 'The SEO meta description for search engine results. Should summarize the post content in 150-160 characters.',
        },
        og_title: {
          type: 'string',
          required: false,
          label: 'Open Graph Title',
          description: 'Facebook/Open Graph title',
          aiControlled: true,
          aiDescription: 'The title displayed when the post is shared on Facebook and other social platforms using Open Graph.',
        },
        og_description: {
          type: 'string',
          required: false,
          label: 'Open Graph Description',
          inputType: 'textarea',
          description: 'Facebook/Open Graph description',
          aiControlled: true,
          aiDescription: 'The description displayed when the post is shared on Facebook and other social platforms using Open Graph.',
        },
        og_image: {
          type: 'string',
          required: false,
          label: 'Open Graph Image',
          placeholder: 'https://example.com/image.jpg',
          description: 'Facebook/Open Graph image URL',
          aiControlled: false,
        },
        twitter_title: {
          type: 'string',
          required: false,
          label: 'Twitter Title',
          description: 'Twitter card title',
          aiControlled: true,
          aiDescription: 'The title displayed when the post is shared on Twitter.',
        },
        twitter_description: {
          type: 'string',
          required: false,
          label: 'Twitter Description',
          inputType: 'textarea',
          description: 'Twitter card description',
          aiControlled: true,
          aiDescription: 'The description displayed when the post is shared on Twitter. Should be concise and engaging.',
        },
        twitter_image: {
          type: 'string',
          required: false,
          label: 'Twitter Image',
          placeholder: 'https://example.com/image.jpg',
          description: 'Twitter card image URL',
          aiControlled: false,
        },
        published_at: {
          type: 'string',
          required: false,
          label: 'Published At',
          description: 'Publication date/time in ISO 8601 format',
          aiControlled: false,
        },
        codeinjection_head: {
          type: 'string',
          required: false,
          label: 'Code Injection Head',
          inputType: 'textarea',
          description: 'Code to inject into the post <head>',
          aiControlled: false,
        },
        codeinjection_foot: {
          type: 'string',
          required: false,
          label: 'Code Injection Foot',
          inputType: 'textarea',
          description: 'Code to inject into the post footer',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string', description: 'Post ID' },
        title: { type: 'string', description: 'Post title' },
        slug: { type: 'string', description: 'Post slug' },
        status: { type: 'string', description: 'Post status' },
      },
    },
    {
      id: 'update_post',
      name: 'Update Post',
      description: 'Update an existing post',
      category: 'Post',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/posts/{postId}',
        method: 'PUT',
        baseUrl: '{url}/ghost/api/v2/admin',
        headers: {
          'Content-Type': 'application/json',
        },
      },
      inputSchema: {
        postId: {
          type: 'string',
          required: true,
          label: 'Post ID',
          description: 'The ID of the post to update',
          aiControlled: false,
        },
        contentFormat: {
          type: 'select',
          required: true,
          label: 'Content Format',
          default: 'html',
          options: [
            { label: 'HTML', value: 'html' },
            { label: 'Mobile Doc (JSON)', value: 'mobileDoc' },
            { label: 'Lexical (JSON)', value: 'lexical' },
          ],
          description: 'The format of the post content',
          aiControlled: false,
        },
        title: {
          type: 'string',
          required: false,
          label: 'Title',
          description: 'The post title',
          aiControlled: true,
          aiDescription: 'The title of the blog post. Should be engaging, descriptive, and SEO-friendly.',
        },
        content: {
          type: 'string',
          required: false,
          label: 'Content',
          inputType: 'textarea',
          description: 'The post content (HTML or JSON)',
          aiControlled: true,
          aiDescription: 'The main body content of the blog post. Can include formatted text, headings, paragraphs, lists, and other HTML elements.',
        },
        status: {
          type: 'select',
          required: false,
          label: 'Status',
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Published', value: 'published' },
            { label: 'Scheduled', value: 'scheduled' },
          ],
          description: 'Publication status',
          aiControlled: false,
        },
        slug: {
          type: 'string',
          required: false,
          label: 'Slug',
          description: 'URL-friendly identifier',
          aiControlled: false,
        },
        featured: {
          type: 'boolean',
          required: false,
          label: 'Featured',
          description: 'Mark as featured',
          aiControlled: false,
        },
        authors: {
          type: 'array',
          required: false,
          label: 'Authors',
          description: 'Array of author IDs',
          aiControlled: false,
        },
        tags: {
          type: 'array',
          required: false,
          label: 'Tags',
          description: 'Array of tag names or IDs',
          aiControlled: false,
        },
        canonical_url: {
          type: 'string',
          required: false,
          label: 'Canonical URL',
          description: 'The canonical URL',
          aiControlled: false,
        },
        meta_title: {
          type: 'string',
          required: false,
          label: 'Meta Title',
          description: 'SEO meta title',
          aiControlled: true,
          aiDescription: 'The SEO meta title for search engine results. Should be concise and include relevant keywords.',
        },
        meta_description: {
          type: 'string',
          required: false,
          label: 'Meta Description',
          inputType: 'textarea',
          description: 'SEO meta description',
          aiControlled: true,
          aiDescription: 'The SEO meta description for search engine results. Should summarize the post content in 150-160 characters.',
        },
        og_title: {
          type: 'string',
          required: false,
          label: 'Open Graph Title',
          aiControlled: true,
          aiDescription: 'The title displayed when the post is shared on Facebook and other social platforms using Open Graph.',
        },
        og_description: {
          type: 'string',
          required: false,
          label: 'Open Graph Description',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'The description displayed when the post is shared on Facebook and other social platforms using Open Graph.',
        },
        og_image: {
          type: 'string',
          required: false,
          label: 'Open Graph Image',
          placeholder: 'https://example.com/image.jpg',
          aiControlled: false,
        },
        twitter_title: {
          type: 'string',
          required: false,
          label: 'Twitter Title',
          aiControlled: true,
          aiDescription: 'The title displayed when the post is shared on Twitter.',
        },
        twitter_description: {
          type: 'string',
          required: false,
          label: 'Twitter Description',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'The description displayed when the post is shared on Twitter. Should be concise and engaging.',
        },
        twitter_image: {
          type: 'string',
          required: false,
          label: 'Twitter Image',
          placeholder: 'https://example.com/image.jpg',
          aiControlled: false,
        },
        published_at: {
          type: 'string',
          required: false,
          label: 'Published At',
          description: 'Publication date/time in ISO 8601 format',
          aiControlled: false,
        },
        codeinjection_head: {
          type: 'string',
          required: false,
          label: 'Code Injection Head',
          inputType: 'textarea',
          aiControlled: false,
        },
        codeinjection_foot: {
          type: 'string',
          required: false,
          label: 'Code Injection Foot',
          inputType: 'textarea',
          aiControlled: false,
        },
      },
      outputSchema: {
        post: { type: 'object', description: 'Updated post object' },
      },
    },
    {
      id: 'delete_post',
      name: 'Delete Post',
      description: 'Delete a post',
      category: 'Post',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/posts/{postId}',
        method: 'DELETE',
        baseUrl: '{url}/ghost/api/v2/admin',
        headers: {
          'Content-Type': 'application/json',
        },
      },
      inputSchema: {
        postId: {
          type: 'string',
          required: true,
          label: 'Post ID',
          description: 'The ID of the post to delete',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean', description: 'Deletion success status' },
      },
    },
  ],

  supported_triggers: [],
};
