import { ConnectorDefinition } from '../../shared';

export const POSTHOG_CONNECTOR: ConnectorDefinition = {
  name: 'posthog',
  display_name: 'PostHog',
  category: 'analytics',
  description: 'Product analytics platform for tracking events, users, and feature flags',
  auth_type: 'api_key',
  verified: false,

  auth_fields: [
    {
      key: 'url',
      label: 'Instance URL',
      type: 'string',
      required: true,
      placeholder: 'https://app.posthog.com',
      description: 'Your PostHog instance URL',
      default: 'https://app.posthog.com',
      helpUrl: 'https://posthog.com/docs',
      helpText: 'PostHog documentation',
    },
    {
      key: 'apiKey',
      label: 'API Key',
      type: 'password',
      required: true,
      placeholder: 'Enter your PostHog API key',
      description: 'Your PostHog project API key',
      helpUrl: 'https://posthog.com/docs/api',
      helpText: 'How to get your API key',
    },
  ],

  endpoints: {
    base_url: '{url}',
    batch: '/batch',
    capture: '/capture',
  },

  webhook_support: true,

  rate_limits: {
    requests_per_second: 10,
  },

  supported_actions: [
    // Event Actions
    {
      id: 'create_event',
      name: 'Create Event',
      description: 'Capture an analytics event',
      category: 'Event',
      icon: 'activity',
      verified: false,
      api: {
        endpoint: '/capture',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          eventName: 'event',
          distinctId: 'distinct_id',
          properties: 'properties',
          timestamp: 'timestamp',
        },
      },
      inputSchema: {
        eventName: {
          type: 'string',
          required: true,
          label: 'Event Name',
          placeholder: 'button_clicked',
          description: 'Name of the event to track',
          aiControlled: false,
        },
        distinctId: {
          type: 'string',
          required: true,
          label: 'Distinct ID',
          placeholder: 'user@example.com',
          description: 'Unique identifier for the user',
          aiControlled: false,
        },
        properties: {
          type: 'object',
          required: false,
          label: 'Properties',
          description: 'Additional event properties as key-value pairs',
          aiControlled: false,
        },
        timestamp: {
          type: 'string',
          required: false,
          label: 'Timestamp',
          description: 'ISO 8601 timestamp (defaults to current time)',
          aiControlled: false,
        },
      },
      outputSchema: {
        status: { type: 'number', description: 'Response status code' },
        success: { type: 'boolean', description: 'Whether the event was captured' },
      },
    },
    // Alias Actions
    {
      id: 'create_alias',
      name: 'Create Alias',
      description: 'Create an alias to associate two distinct IDs',
      category: 'Identity',
      icon: 'link',
      verified: false,
      api: {
        endpoint: '/batch',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          distinctId: 'properties.distinct_id',
          alias: 'properties.alias',
          context: 'context',
          timestamp: 'timestamp',
        },
      },
      inputSchema: {
        distinctId: {
          type: 'string',
          required: true,
          label: 'Distinct ID',
          placeholder: 'user123',
          description: 'The user\'s current distinct ID',
          aiControlled: false,
        },
        alias: {
          type: 'string',
          required: true,
          label: 'Alias',
          placeholder: 'user@example.com',
          description: 'The new alias to associate with this user',
          aiControlled: false,
        },
        context: {
          type: 'object',
          required: false,
          label: 'Context',
          description: 'Additional context information',
          aiControlled: false,
        },
        timestamp: {
          type: 'string',
          required: false,
          label: 'Timestamp',
          description: 'ISO 8601 timestamp (defaults to current time)',
          aiControlled: false,
        },
      },
      outputSchema: {
        status: { type: 'number', description: 'Response status code' },
        success: { type: 'boolean', description: 'Whether the alias was created' },
      },
    },
    // Identity Actions
    {
      id: 'create_identity',
      name: 'Create Identity',
      description: 'Identify a user and set their properties',
      category: 'Identity',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/batch',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          distinctId: 'distinct_id',
          properties: 'properties',
          timestamp: 'timestamp',
          messageId: 'messageId',
        },
      },
      inputSchema: {
        distinctId: {
          type: 'string',
          required: true,
          label: 'Distinct ID',
          placeholder: 'user@example.com',
          description: 'The user\'s unique identifier',
          aiControlled: false,
        },
        properties: {
          type: 'object',
          required: false,
          label: 'Properties',
          description: 'User properties to set (e.g., email, name, plan)',
          aiControlled: false,
        },
        messageId: {
          type: 'string',
          required: false,
          label: 'Message ID',
          description: 'Unique message identifier for deduplication',
          aiControlled: false,
        },
        timestamp: {
          type: 'string',
          required: false,
          label: 'Timestamp',
          description: 'ISO 8601 timestamp (defaults to current time)',
          aiControlled: false,
        },
      },
      outputSchema: {
        status: { type: 'number', description: 'Response status code' },
        success: { type: 'boolean', description: 'Whether the identity was created' },
      },
    },
    // Track Page
    {
      id: 'track_page',
      name: 'Track Page View',
      description: 'Track a page view event',
      category: 'Track',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/batch',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          distinctId: 'distinct_id',
          name: 'name',
          category: 'category',
          properties: 'properties',
          context: 'context',
          messageId: 'messageId',
          timestamp: 'timestamp',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Page Name',
          placeholder: 'Home Page',
          description: 'Name of the page being tracked',
          aiControlled: false,
        },
        distinctId: {
          type: 'string',
          required: true,
          label: 'Distinct ID',
          placeholder: 'user@example.com',
          description: 'The user\'s unique identifier',
          aiControlled: false,
        },
        category: {
          type: 'string',
          required: false,
          label: 'Category',
          placeholder: 'Marketing',
          description: 'Page category',
          aiControlled: false,
        },
        properties: {
          type: 'object',
          required: false,
          label: 'Properties',
          description: 'Additional page properties (e.g., url, title, path)',
          aiControlled: false,
        },
        context: {
          type: 'object',
          required: false,
          label: 'Context',
          description: 'Context information (e.g., ip, userAgent)',
          aiControlled: false,
        },
        messageId: {
          type: 'string',
          required: false,
          label: 'Message ID',
          description: 'Unique message identifier',
          aiControlled: false,
        },
        timestamp: {
          type: 'string',
          required: false,
          label: 'Timestamp',
          description: 'ISO 8601 timestamp (defaults to current time)',
          aiControlled: false,
        },
      },
      outputSchema: {
        status: { type: 'number', description: 'Response status code' },
        success: { type: 'boolean', description: 'Whether the page view was tracked' },
      },
    },
    // Track Screen
    {
      id: 'track_screen',
      name: 'Track Screen View',
      description: 'Track a screen view event (mobile)',
      category: 'Track',
      icon: 'smartphone',
      verified: false,
      api: {
        endpoint: '/batch',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
        },
        paramMapping: {
          distinctId: 'distinct_id',
          name: 'name',
          category: 'category',
          properties: 'properties',
          context: 'context',
          messageId: 'messageId',
          timestamp: 'timestamp',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Screen Name',
          placeholder: 'Dashboard Screen',
          description: 'Name of the screen being tracked',
          aiControlled: false,
        },
        distinctId: {
          type: 'string',
          required: true,
          label: 'Distinct ID',
          placeholder: 'user@example.com',
          description: 'The user\'s unique identifier',
          aiControlled: false,
        },
        category: {
          type: 'string',
          required: false,
          label: 'Category',
          placeholder: 'App',
          description: 'Screen category',
          aiControlled: false,
        },
        properties: {
          type: 'object',
          required: false,
          label: 'Properties',
          description: 'Additional screen properties',
          aiControlled: false,
        },
        context: {
          type: 'object',
          required: false,
          label: 'Context',
          description: 'Context information (e.g., device, os)',
          aiControlled: false,
        },
        messageId: {
          type: 'string',
          required: false,
          label: 'Message ID',
          description: 'Unique message identifier',
          aiControlled: false,
        },
        timestamp: {
          type: 'string',
          required: false,
          label: 'Timestamp',
          description: 'ISO 8601 timestamp (defaults to current time)',
          aiControlled: false,
        },
      },
      outputSchema: {
        status: { type: 'number', description: 'Response status code' },
        success: { type: 'boolean', description: 'Whether the screen view was tracked' },
      },
    },
  ],

  supported_triggers: [],
};
