import { ConnectorDefinition } from '../../shared';

export const DISCOURSE_CONNECTOR: ConnectorDefinition = {
  name: 'discourse',
  display_name: 'Discourse',
  category: 'communication',
  description: 'Open source discussion platform and community forum',
  auth_type: 'api_key',
  verified: false,

  auth_fields: [
    {
      key: 'url',
      label: 'URL',
      type: 'string',
      required: true,
      placeholder: 'https://discourse.example.com',
      description: 'Your Discourse instance URL',
      helpText: 'Enter your Discourse forum URL',
    },
    {
      key: 'apiKey',
      label: 'API Key',
      type: 'password',
      required: true,
      placeholder: 'Enter your Discourse API key',
      description: 'Your Discourse API key',
      helpUrl: 'https://docs.discourse.org/#tag/API-Documentation',
      helpText: 'How to get your API key',
    },
    {
      key: 'username',
      label: 'API Username',
      type: 'string',
      required: true,
      placeholder: 'Enter your username',
      description: 'Username for API authentication',
      helpText: 'Username associated with the API key',
    },
  ],

  endpoints: {
    base_url: '{url}',
    categories: '/categories.json',
    groups: '/groups.json',
    posts: '/posts.json',
    users: '/admin/users/list/{flag}.json',
    user_groups: '/groups/{groupId}/members.json',
  },

  webhook_support: false,

  rate_limits: {
    requests_per_second: 10,
  },

  supported_actions: [
    // Category Actions
    {
      id: 'create_category',
      name: 'Create Category',
      description: 'Create a new category',
      category: 'Category',
      icon: 'folder',
      verified: false,
      api: {
        endpoint: '/categories.json',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
        paramMapping: {
          name: 'name',
          color: 'color',
          textColor: 'text_color',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Name',
          description: 'Name of the category',
          aiControlled: true,
          aiDescription: 'Generate a descriptive and clear category name for the forum',
        },
        color: {
          type: 'string',
          required: true,
          label: 'Color',
          description: 'Color hex code (e.g., 0000FF)',
          default: '0000FF',
          aiControlled: false,
        },
        textColor: {
          type: 'string',
          required: true,
          label: 'Text Color',
          description: 'Text color hex code (e.g., FFFFFF)',
          default: 'FFFFFF',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'number', description: 'Category ID' },
        name: { type: 'string' },
        color: { type: 'string' },
        text_color: { type: 'string' },
      },
    },
    {
      id: 'get_all_categories',
      name: 'Get All Categories',
      description: 'Get all categories',
      category: 'Category',
      icon: 'folder',
      verified: false,
      api: {
        endpoint: '/categories.json',
        method: 'GET',
        baseUrl: '{url}',
        headers: {
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        returnAll: {
          type: 'boolean',
          required: false,
          label: 'Return All',
          description: 'Whether to return all results or only up to a given limit',
          default: false,
          aiControlled: false,
        },
        limit: {
          type: 'number',
          required: false,
          label: 'Limit',
          description: 'Max number of results to return',
          default: 50,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        categories: {
          type: 'array',
          description: 'List of categories',
        },
      },
    },
    {
      id: 'update_category',
      name: 'Update Category',
      description: 'Update an existing category',
      category: 'Category',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/categories/{categoryId}.json',
        method: 'PUT',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        categoryId: {
          type: 'string',
          required: true,
          label: 'Category ID',
          description: 'ID of the category to update',
          aiControlled: false,
        },
        name: {
          type: 'string',
          required: true,
          label: 'Name',
          description: 'New name of the category',
          aiControlled: true,
          aiDescription: 'Generate a descriptive and clear category name for the forum',
        },
        color: {
          type: 'string',
          required: false,
          label: 'Color',
          description: 'Color hex code',
          aiControlled: false,
        },
        textColor: {
          type: 'string',
          required: false,
          label: 'Text Color',
          description: 'Text color hex code',
          aiControlled: false,
        },
      },
      outputSchema: {
        category: { type: 'object' },
      },
    },
    // Group Actions
    {
      id: 'create_group',
      name: 'Create Group',
      description: 'Create a new group',
      category: 'Group',
      icon: 'users',
      verified: false,
      api: {
        endpoint: '/admin/groups.json',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Name',
          description: 'Name of the group',
          aiControlled: true,
          aiDescription: 'Generate a descriptive group name for the forum community',
        },
      },
      outputSchema: {
        id: { type: 'number', description: 'Group ID' },
        name: { type: 'string' },
      },
    },
    {
      id: 'get_group',
      name: 'Get Group',
      description: 'Get a specific group',
      category: 'Group',
      icon: 'users',
      verified: false,
      api: {
        endpoint: '/groups/{name}',
        method: 'GET',
        baseUrl: '{url}',
        headers: {
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Name',
          description: 'Name of the group',
          aiControlled: false,
        },
      },
      outputSchema: {
        group: { type: 'object' },
      },
    },
    {
      id: 'get_all_groups',
      name: 'Get All Groups',
      description: 'Get all groups',
      category: 'Group',
      icon: 'users',
      verified: false,
      api: {
        endpoint: '/groups.json',
        method: 'GET',
        baseUrl: '{url}',
        headers: {
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        returnAll: {
          type: 'boolean',
          required: false,
          label: 'Return All',
          description: 'Whether to return all results or only up to a given limit',
          default: false,
          aiControlled: false,
        },
        limit: {
          type: 'number',
          required: false,
          label: 'Limit',
          description: 'Max number of results to return',
          default: 50,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        groups: { type: 'array' },
      },
    },
    {
      id: 'update_group',
      name: 'Update Group',
      description: 'Update an existing group',
      category: 'Group',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/groups/{groupId}.json',
        method: 'PUT',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        groupId: {
          type: 'string',
          required: true,
          label: 'Group ID',
          description: 'ID of the group to update',
          aiControlled: false,
        },
        name: {
          type: 'string',
          required: true,
          label: 'Name',
          description: 'New name of the group',
          aiControlled: true,
          aiDescription: 'Generate a descriptive group name for the forum community',
        },
      },
      outputSchema: {
        group: { type: 'object' },
      },
    },
    // Post Actions
    {
      id: 'create_post',
      name: 'Create Post',
      description: 'Create a new post',
      category: 'Post',
      icon: 'message-square',
      verified: false,
      api: {
        endpoint: '/posts.json',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
        paramMapping: {
          title: 'title',
          content: 'raw',
          category: 'category',
          topicId: 'topic_id',
          replyToPostNumber: 'reply_to_post_number',
        },
      },
      inputSchema: {
        title: {
          type: 'string',
          required: false,
          label: 'Title',
          description: 'Title of the post',
          aiControlled: true,
          aiDescription: 'Generate an engaging and descriptive title for the forum post or topic',
        },
        content: {
          type: 'string',
          required: true,
          label: 'Content',
          inputType: 'textarea',
          description: 'Content of the post',
          aiControlled: true,
          aiDescription: 'Generate the main content for the forum post. Use appropriate formatting and structure for readability',
        },
        category: {
          type: 'string',
          required: false,
          label: 'Category ID',
          description: 'ID of the category',
          aiControlled: false,
        },
        topicId: {
          type: 'string',
          required: false,
          label: 'Topic ID',
          description: 'ID of the topic (for replies)',
          aiControlled: false,
        },
        replyToPostNumber: {
          type: 'string',
          required: false,
          label: 'Reply To Post Number',
          description: 'The number of the post to reply to',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'number', description: 'Post ID' },
        topic_id: { type: 'number' },
        raw: { type: 'string' },
      },
    },
    {
      id: 'get_post',
      name: 'Get Post',
      description: 'Get a specific post',
      category: 'Post',
      icon: 'message-square',
      verified: false,
      api: {
        endpoint: '/posts/{postId}',
        method: 'GET',
        baseUrl: '{url}',
        headers: {
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        postId: {
          type: 'string',
          required: true,
          label: 'Post ID',
          description: 'ID of the post',
          aiControlled: false,
        },
      },
      outputSchema: {
        post: { type: 'object' },
      },
    },
    {
      id: 'get_all_posts',
      name: 'Get All Posts',
      description: 'Get all posts',
      category: 'Post',
      icon: 'message-square',
      verified: false,
      api: {
        endpoint: '/posts.json',
        method: 'GET',
        baseUrl: '{url}',
        headers: {
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        returnAll: {
          type: 'boolean',
          required: false,
          label: 'Return All',
          description: 'Whether to return all results or only up to a given limit',
          default: false,
          aiControlled: false,
        },
        limit: {
          type: 'number',
          required: false,
          label: 'Limit',
          description: 'Max number of results to return',
          default: 50,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        posts: { type: 'array' },
      },
    },
    {
      id: 'update_post',
      name: 'Update Post',
      description: 'Update an existing post',
      category: 'Post',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/posts/{postId}.json',
        method: 'PUT',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
        paramMapping: {
          content: 'raw',
          editReason: 'edit_reason',
          cooked: 'cooked',
        },
      },
      inputSchema: {
        postId: {
          type: 'string',
          required: true,
          label: 'Post ID',
          description: 'ID of the post to update',
          aiControlled: false,
        },
        content: {
          type: 'string',
          required: true,
          label: 'Content',
          inputType: 'textarea',
          description: 'Updated content of the post. HTML is supported.',
          aiControlled: true,
          aiDescription: 'Generate updated content for the forum post. Use appropriate formatting and structure for readability',
        },
        editReason: {
          type: 'string',
          required: false,
          label: 'Edit Reason',
          description: 'Reason for editing the post',
          aiControlled: true,
          aiDescription: 'Generate a brief reason explaining why this post is being edited',
        },
        cooked: {
          type: 'boolean',
          required: false,
          label: 'Cooked',
          description: 'Whether the content is already cooked (processed)',
          default: false,
          aiControlled: false,
        },
      },
      outputSchema: {
        post: { type: 'object' },
      },
    },
    // User Actions
    {
      id: 'create_user',
      name: 'Create User',
      description: 'Create a new user',
      category: 'User',
      icon: 'user-plus',
      verified: false,
      api: {
        endpoint: '/users.json',
        method: 'POST',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Name',
          description: 'Name of the user',
          aiControlled: false,
        },
        email: {
          type: 'string',
          required: true,
          label: 'Email',
          inputType: 'email',
          placeholder: 'name@email.com',
          description: 'Email address of the user',
          aiControlled: false,
        },
        username: {
          type: 'string',
          required: true,
          label: 'Username',
          description: 'Username for the user',
          aiControlled: false,
        },
        password: {
          type: 'string',
          required: true,
          label: 'Password',
          inputType: 'password',
          description: 'Password for the user',
          aiControlled: false,
        },
        active: {
          type: 'boolean',
          required: false,
          label: 'Active',
          description: 'Whether the user is active',
          default: false,
          aiControlled: false,
        },
        approved: {
          type: 'boolean',
          required: false,
          label: 'Approved',
          description: 'Whether the user is approved',
          default: false,
          aiControlled: false,
        },
      },
      outputSchema: {
        user_id: { type: 'number', description: 'User ID' },
        username: { type: 'string' },
      },
    },
    {
      id: 'get_user',
      name: 'Get User',
      description: 'Get a user by username or external ID',
      category: 'User',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/users/{identifier}',
        method: 'GET',
        baseUrl: '{url}',
        headers: {
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        by: {
          type: 'select',
          required: true,
          label: 'Get By',
          description: 'What to search by',
          default: 'username',
          options: [
            { label: 'Username', value: 'username' },
            { label: 'SSO External ID', value: 'externalId' },
          ],
          aiControlled: false,
        },
        username: {
          type: 'string',
          required: false,
          label: 'Username',
          description: 'The username of the user to return',
          aiControlled: false,
        },
        externalId: {
          type: 'string',
          required: false,
          label: 'SSO External ID',
          description: 'Discourse SSO external ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        user: { type: 'object' },
      },
    },
    {
      id: 'get_all_users',
      name: 'Get All Users',
      description: 'Get all users with optional filtering',
      category: 'User',
      icon: 'users',
      verified: false,
      api: {
        endpoint: '/admin/users/list/{flag}.json',
        method: 'GET',
        baseUrl: '{url}',
        headers: {
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        flag: {
          type: 'select',
          required: true,
          label: 'Flag',
          description: 'User flags to search for',
          default: 'active',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Blocked', value: 'blocked' },
            { label: 'New', value: 'new' },
            { label: 'Staff', value: 'staff' },
            { label: 'Suspect', value: 'suspect' },
            { label: 'Suspended', value: 'suspended' },
          ],
          aiControlled: false,
        },
        returnAll: {
          type: 'boolean',
          required: false,
          label: 'Return All',
          description: 'Whether to return all results or only up to a given limit',
          default: false,
          aiControlled: false,
        },
        limit: {
          type: 'number',
          required: false,
          label: 'Limit',
          description: 'Max number of results to return',
          default: 50,
          min: 1,
          max: 100,
          aiControlled: false,
        },
        stats: {
          type: 'boolean',
          required: false,
          label: 'Include Stats',
          description: 'Whether to return user stats',
          default: false,
          aiControlled: false,
        },
        asc: {
          type: 'boolean',
          required: false,
          label: 'Ascending',
          description: 'Whether to sort ascending',
          default: true,
          aiControlled: false,
        },
        showEmails: {
          type: 'boolean',
          required: false,
          label: 'Show Emails',
          description: 'Whether to include user email addresses',
          default: false,
          aiControlled: false,
        },
        order: {
          type: 'select',
          required: false,
          label: 'Order By',
          description: 'What to order by',
          default: 'created',
          options: [
            { label: 'Created', value: 'created' },
            { label: 'Days Visited', value: 'days_visited' },
            { label: 'Email', value: 'email' },
            { label: 'Last Emailed', value: 'last_emailed' },
            { label: 'Posts', value: 'posts' },
            { label: 'Posts Read', value: 'posts_read' },
            { label: 'Read Time', value: 'read_time' },
            { label: 'Seen', value: 'seen' },
            { label: 'Topics Viewed', value: 'topics_viewed' },
            { label: 'Trust Level', value: 'trust_level' },
            { label: 'Username', value: 'username' },
          ],
          aiControlled: false,
        },
      },
      outputSchema: {
        users: { type: 'array' },
      },
    },
    // User Group Actions
    {
      id: 'add_user_to_group',
      name: 'Add User to Group',
      description: 'Add a user to a group',
      category: 'User Group',
      icon: 'user-plus',
      verified: false,
      api: {
        endpoint: '/groups/{groupId}/members.json',
        method: 'PUT',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        groupId: {
          type: 'string',
          required: true,
          label: 'Group ID',
          description: 'ID of the group',
          aiControlled: false,
        },
        usernames: {
          type: 'string',
          required: true,
          label: 'Usernames',
          description: 'Usernames to add to group. Multiple can be defined separated by comma.',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    {
      id: 'remove_user_from_group',
      name: 'Remove User from Group',
      description: 'Remove a user from a group',
      category: 'User Group',
      icon: 'user-minus',
      verified: false,
      api: {
        endpoint: '/groups/{groupId}/members.json',
        method: 'DELETE',
        baseUrl: '{url}',
        headers: {
          'Content-Type': 'application/json',
          'Api-Key': '{apiKey}',
          'Api-Username': '{username}',
        },
      },
      inputSchema: {
        groupId: {
          type: 'string',
          required: true,
          label: 'Group ID',
          description: 'ID of the group',
          aiControlled: false,
        },
        usernames: {
          type: 'string',
          required: true,
          label: 'Usernames',
          description: 'Usernames to remove from group. Multiple can be defined separated by comma.',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
  ],

  supported_triggers: [],
};
