import { ConnectorDefinition } from '../../shared';

export const HARVEST_CONNECTOR: ConnectorDefinition = {
  name: 'harvest',
  display_name: 'Harvest',
  category: 'productivity',
  description: 'Time tracking, invoicing, and business insights platform',
  auth_type: 'bearer_token',
  verified: false,

  auth_fields: [
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
      placeholder: 'Enter your Harvest access token',
      description: 'Your Harvest personal access token',
      helpUrl: 'https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/',
      helpText: 'How to get your access token',
    },
    {
      key: 'accountId',
      label: 'Account ID',
      type: 'string',
      required: true,
      placeholder: 'Enter your Harvest account ID',
      description: 'Your Harvest account ID',
      helpUrl: 'https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/',
      helpText: 'How to find your account ID',
    },
  ],

  endpoints: {
    base_url: 'https://api.harvestapp.com/v2',
    time_entries: '/time_entries',
    projects: '/projects',
    tasks: '/tasks',
    clients: '/clients',
    contacts: '/contacts',
    users: '/users',
    invoices: '/invoices',
    estimates: '/estimates',
    expenses: '/expenses',
    company: '/company',
  },

  webhook_support: false,

  rate_limits: {
    requests_per_second: 100,
  },

  supported_actions: [
    // Time Entry Actions
    {
      id: 'create_time_entry_by_duration',
      name: 'Create Time Entry by Duration',
      description: 'Create a new time entry using duration',
      category: 'Time Entry',
      icon: 'clock',
      verified: false,
      api: {
        endpoint: '/time_entries',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          projectId: 'project_id',
          taskId: 'task_id',
          spentDate: 'spent_date',
          hours: 'hours',
          notes: 'notes',
          userId: 'user_id',
        },
      },
      inputSchema: {
        projectId: {
          type: 'string',
          required: true,
          label: 'Project ID',
          description: 'The ID of the project to associate with the time entry',
          aiControlled: false,
        },
        taskId: {
          type: 'string',
          required: true,
          label: 'Task ID',
          description: 'The ID of the task to associate with the time entry',
          aiControlled: false,
        },
        spentDate: {
          type: 'string',
          required: true,
          label: 'Spent Date',
          description: 'The ISO 8601 formatted date the time entry was spent',
          placeholder: '2024-01-09',
          aiControlled: false,
        },
        hours: {
          type: 'number',
          required: false,
          label: 'Hours',
          description: 'The number of hours tracked',
          min: 0,
          default: 0,
          aiControlled: false,
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          description: 'Notes about the time entry',
          aiControlled: true,
          aiDescription: 'Generate descriptive notes summarizing the work performed during this time entry',
        },
        userId: {
          type: 'string',
          required: false,
          label: 'User ID',
          description: 'The ID of the user (defaults to authenticated user)',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string', description: 'Time entry ID' },
        spent_date: { type: 'string' },
        hours: { type: 'number' },
        notes: { type: 'string' },
        project: { type: 'object' },
        task: { type: 'object' },
      },
    },
    {
      id: 'create_time_entry_by_start_end',
      name: 'Create Time Entry by Start/End Time',
      description: 'Create a new time entry using start and end time',
      category: 'Time Entry',
      icon: 'clock',
      verified: false,
      api: {
        endpoint: '/time_entries',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          projectId: 'project_id',
          taskId: 'task_id',
          spentDate: 'spent_date',
          startedTime: 'started_time',
          endedTime: 'ended_time',
          notes: 'notes',
          userId: 'user_id',
        },
      },
      inputSchema: {
        projectId: {
          type: 'string',
          required: true,
          label: 'Project ID',
          description: 'The ID of the project to associate with the time entry',
          aiControlled: false,
        },
        taskId: {
          type: 'string',
          required: true,
          label: 'Task ID',
          description: 'The ID of the task to associate with the time entry',
          aiControlled: false,
        },
        spentDate: {
          type: 'string',
          required: true,
          label: 'Spent Date',
          description: 'The ISO 8601 formatted date the time entry was spent',
          placeholder: '2024-01-09',
          aiControlled: false,
        },
        startedTime: {
          type: 'string',
          required: false,
          label: 'Started Time',
          description: 'The time the entry started (e.g., "8:00am")',
          placeholder: '8:00am',
          aiControlled: false,
        },
        endedTime: {
          type: 'string',
          required: false,
          label: 'Ended Time',
          description: 'The time the entry ended (e.g., "3:00pm")',
          placeholder: '3:00pm',
          aiControlled: false,
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          description: 'Notes about the time entry',
          aiControlled: true,
          aiDescription: 'Generate descriptive notes summarizing the work performed during this time entry',
        },
        userId: {
          type: 'string',
          required: false,
          label: 'User ID',
          description: 'The ID of the user (defaults to authenticated user)',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string', description: 'Time entry ID' },
        spent_date: { type: 'string' },
        started_time: { type: 'string' },
        ended_time: { type: 'string' },
        notes: { type: 'string' },
        project: { type: 'object' },
        task: { type: 'object' },
      },
    },
    {
      id: 'get_time_entry',
      name: 'Get Time Entry',
      description: 'Get a specific time entry',
      category: 'Time Entry',
      icon: 'clock',
      verified: false,
      api: {
        endpoint: '/time_entries/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Time Entry ID',
          description: 'The ID of the time entry to retrieve',
          aiControlled: false,
        },
      },
      outputSchema: {
        timeEntry: { type: 'object', description: 'Time entry details' },
      },
    },
    {
      id: 'get_all_time_entries',
      name: 'Get All Time Entries',
      description: 'Get all time entries with optional filters',
      category: 'Time Entry',
      icon: 'list',
      verified: false,
      api: {
        endpoint: '/time_entries',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        userId: {
          type: 'string',
          required: false,
          label: 'User ID',
          description: 'Filter by user ID',
          aiControlled: false,
        },
        clientId: {
          type: 'string',
          required: false,
          label: 'Client ID',
          description: 'Filter by client ID',
          aiControlled: false,
        },
        projectId: {
          type: 'string',
          required: false,
          label: 'Project ID',
          description: 'Filter by project ID',
          aiControlled: false,
        },
        isBilled: {
          type: 'boolean',
          required: false,
          label: 'Is Billed',
          description: 'Filter by billed status',
          aiControlled: false,
        },
        isRunning: {
          type: 'boolean',
          required: false,
          label: 'Is Running',
          description: 'Filter by running status',
          aiControlled: false,
        },
        from: {
          type: 'string',
          required: false,
          label: 'From Date',
          description: 'Only return time entries on or after this date',
          placeholder: '2024-01-01',
          aiControlled: false,
        },
        to: {
          type: 'string',
          required: false,
          label: 'To Date',
          description: 'Only return time entries on or before this date',
          placeholder: '2024-12-31',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          description: 'Only return entries updated since this date/time',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          description: 'Page number for pagination',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          description: 'Number of results per page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        time_entries: { type: 'array', description: 'List of time entries' },
        per_page: { type: 'number' },
        total_pages: { type: 'number' },
        total_entries: { type: 'number' },
      },
    },
    {
      id: 'update_time_entry',
      name: 'Update Time Entry',
      description: 'Update an existing time entry',
      category: 'Time Entry',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/time_entries/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          projectId: 'project_id',
          taskId: 'task_id',
          spentDate: 'spent_date',
          startedTime: 'started_time',
          endedTime: 'ended_time',
          hours: 'hours',
          notes: 'notes',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Time Entry ID',
          description: 'The ID of the time entry to update',
          aiControlled: false,
        },
        projectId: {
          type: 'string',
          required: false,
          label: 'Project ID',
          aiControlled: false,
        },
        taskId: {
          type: 'string',
          required: false,
          label: 'Task ID',
          aiControlled: false,
        },
        spentDate: {
          type: 'string',
          required: false,
          label: 'Spent Date',
          aiControlled: false,
        },
        startedTime: {
          type: 'string',
          required: false,
          label: 'Started Time',
          placeholder: '8:00am',
          aiControlled: false,
        },
        endedTime: {
          type: 'string',
          required: false,
          label: 'Ended Time',
          placeholder: '3:00pm',
          aiControlled: false,
        },
        hours: {
          type: 'number',
          required: false,
          label: 'Hours',
          min: 0,
          aiControlled: false,
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'Generate descriptive notes summarizing the work performed during this time entry',
        },
      },
      outputSchema: {
        timeEntry: { type: 'object' },
      },
    },
    {
      id: 'delete_time_entry',
      name: 'Delete Time Entry',
      description: 'Delete a time entry',
      category: 'Time Entry',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/time_entries/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Time Entry ID',
          description: 'The ID of the time entry to delete',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    {
      id: 'restart_time_entry',
      name: 'Restart Time Entry',
      description: 'Restart a stopped time entry',
      category: 'Time Entry',
      icon: 'play',
      verified: false,
      api: {
        endpoint: '/time_entries/{id}/restart',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Time Entry ID',
          description: 'The ID of the time entry to restart',
          aiControlled: false,
        },
      },
      outputSchema: {
        timeEntry: { type: 'object' },
      },
    },
    {
      id: 'stop_time_entry',
      name: 'Stop Time Entry',
      description: 'Stop a running time entry',
      category: 'Time Entry',
      icon: 'stop-circle',
      verified: false,
      api: {
        endpoint: '/time_entries/{id}/stop',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Time Entry ID',
          description: 'The ID of the time entry to stop',
          aiControlled: false,
        },
      },
      outputSchema: {
        timeEntry: { type: 'object' },
      },
    },
    {
      id: 'delete_time_entry_external_reference',
      name: 'Delete Time Entry External Reference',
      description: "Delete a time entry's external reference",
      category: 'Time Entry',
      icon: 'link-2-off',
      verified: false,
      api: {
        endpoint: '/time_entries/{id}/external_reference',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Time Entry ID',
          description: 'The ID of the time entry',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Client Actions
    {
      id: 'create_client',
      name: 'Create Client',
      description: 'Create a new client',
      category: 'Client',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/clients',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          name: 'name',
          isActive: 'is_active',
          address: 'address',
          currency: 'currency',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Client Name',
          description: 'The name of the client',
          aiControlled: true,
          aiDescription: 'Generate an appropriate client name based on the context',
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          description: 'Whether the client is active',
          default: true,
          aiControlled: false,
        },
        address: {
          type: 'string',
          required: false,
          label: 'Address',
          inputType: 'textarea',
          description: 'Physical address of the client',
          aiControlled: false,
        },
        currency: {
          type: 'string',
          required: false,
          label: 'Currency',
          description: 'Currency code (e.g., USD, EUR)',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        name: { type: 'string' },
        is_active: { type: 'boolean' },
        address: { type: 'string' },
        currency: { type: 'string' },
      },
    },
    {
      id: 'get_client',
      name: 'Get Client',
      description: 'Get a specific client',
      category: 'Client',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/clients/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Client ID',
          description: 'The ID of the client to retrieve',
          aiControlled: false,
        },
      },
      outputSchema: {
        client: { type: 'object' },
      },
    },
    {
      id: 'get_all_clients',
      name: 'Get All Clients',
      description: 'Get all clients',
      category: 'Client',
      icon: 'users',
      verified: false,
      api: {
        endpoint: '/clients',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          description: 'Filter by active status',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          description: 'Only return clients updated since this date/time',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        clients: { type: 'array' },
      },
    },
    {
      id: 'update_client',
      name: 'Update Client',
      description: 'Update an existing client',
      category: 'Client',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/clients/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          name: 'name',
          isActive: 'is_active',
          address: 'address',
          currency: 'currency',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Client ID',
          description: 'The ID of the client to update',
          aiControlled: false,
        },
        name: {
          type: 'string',
          required: false,
          label: 'Client Name',
          aiControlled: true,
          aiDescription: 'Generate an appropriate client name based on the context',
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          aiControlled: false,
        },
        address: {
          type: 'string',
          required: false,
          label: 'Address',
          inputType: 'textarea',
          aiControlled: false,
        },
        currency: {
          type: 'string',
          required: false,
          label: 'Currency',
          aiControlled: false,
        },
      },
      outputSchema: {
        client: { type: 'object' },
      },
    },
    {
      id: 'delete_client',
      name: 'Delete Client',
      description: 'Delete a client',
      category: 'Client',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/clients/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Client ID',
          description: 'The ID of the client to delete',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Project Actions
    {
      id: 'create_project',
      name: 'Create Project',
      description: 'Create a new project',
      category: 'Project',
      icon: 'folder',
      verified: false,
      api: {
        endpoint: '/projects',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          clientId: 'client_id',
          name: 'name',
          isBillable: 'is_billable',
          billBy: 'bill_by',
          budgetBy: 'budget_by',
          code: 'code',
          isActive: 'is_active',
          isFixedFee: 'is_fixed_fee',
          hourlyRate: 'hourly_rate',
        },
      },
      inputSchema: {
        clientId: {
          type: 'string',
          required: true,
          label: 'Client ID',
          description: 'The ID of the client',
          aiControlled: false,
        },
        name: {
          type: 'string',
          required: true,
          label: 'Project Name',
          description: 'The name of the project',
          aiControlled: true,
          aiDescription: 'Generate a descriptive project name based on the context',
        },
        isBillable: {
          type: 'boolean',
          required: true,
          label: 'Is Billable',
          description: 'Whether the project is billable',
          aiControlled: false,
        },
        billBy: {
          type: 'string',
          required: true,
          label: 'Bill By',
          description: 'How the project is billed (Project, Tasks, People, or None)',
          aiControlled: false,
        },
        budgetBy: {
          type: 'string',
          required: true,
          label: 'Budget By',
          description: 'How the project is budgeted',
          aiControlled: false,
        },
        code: {
          type: 'string',
          required: false,
          label: 'Project Code',
          description: 'Project code',
          aiControlled: false,
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          default: true,
          aiControlled: false,
        },
        isFixedFee: {
          type: 'boolean',
          required: false,
          label: 'Is Fixed Fee',
          aiControlled: false,
        },
        hourlyRate: {
          type: 'number',
          required: false,
          label: 'Hourly Rate',
          min: 0,
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        name: { type: 'string' },
        client: { type: 'object' },
        is_billable: { type: 'boolean' },
      },
    },
    {
      id: 'get_project',
      name: 'Get Project',
      description: 'Get a specific project',
      category: 'Project',
      icon: 'folder',
      verified: false,
      api: {
        endpoint: '/projects/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Project ID',
          description: 'The ID of the project to retrieve',
          aiControlled: false,
        },
      },
      outputSchema: {
        project: { type: 'object' },
      },
    },
    {
      id: 'get_all_projects',
      name: 'Get All Projects',
      description: 'Get all projects',
      category: 'Project',
      icon: 'folder',
      verified: false,
      api: {
        endpoint: '/projects',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          aiControlled: false,
        },
        clientId: {
          type: 'string',
          required: false,
          label: 'Client ID',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        projects: { type: 'array' },
      },
    },
    {
      id: 'update_project',
      name: 'Update Project',
      description: 'Update an existing project',
      category: 'Project',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/projects/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Project ID',
          aiControlled: false,
        },
        name: {
          type: 'string',
          required: false,
          label: 'Project Name',
          aiControlled: true,
          aiDescription: 'Generate a descriptive project name based on the context',
        },
        code: {
          type: 'string',
          required: false,
          label: 'Project Code',
          aiControlled: false,
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          aiControlled: false,
        },
        isBillable: {
          type: 'boolean',
          required: false,
          label: 'Is Billable',
          aiControlled: false,
        },
        billBy: {
          type: 'string',
          required: false,
          label: 'Bill By',
          aiControlled: false,
        },
        budgetBy: {
          type: 'string',
          required: false,
          label: 'Budget By',
          aiControlled: false,
        },
      },
      outputSchema: {
        project: { type: 'object' },
      },
    },
    {
      id: 'delete_project',
      name: 'Delete Project',
      description: 'Delete a project',
      category: 'Project',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/projects/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Project ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Task Actions
    {
      id: 'create_task',
      name: 'Create Task',
      description: 'Create a new task',
      category: 'Task',
      icon: 'check-square',
      verified: false,
      api: {
        endpoint: '/tasks',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          name: 'name',
          billableByDefault: 'billable_by_default',
          defaultHourlyRate: 'default_hourly_rate',
          isDefault: 'is_default',
          isActive: 'is_active',
        },
      },
      inputSchema: {
        name: {
          type: 'string',
          required: true,
          label: 'Task Name',
          description: 'The name of the task',
          aiControlled: true,
          aiDescription: 'Generate a descriptive task name based on the context',
        },
        billableByDefault: {
          type: 'boolean',
          required: false,
          label: 'Billable by Default',
          description: 'Whether the task is billable by default',
          aiControlled: false,
        },
        defaultHourlyRate: {
          type: 'number',
          required: false,
          label: 'Default Hourly Rate',
          min: 0,
          aiControlled: false,
        },
        isDefault: {
          type: 'boolean',
          required: false,
          label: 'Is Default',
          aiControlled: false,
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          default: true,
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        name: { type: 'string' },
        billable_by_default: { type: 'boolean' },
      },
    },
    {
      id: 'get_task',
      name: 'Get Task',
      description: 'Get a specific task',
      category: 'Task',
      icon: 'check-square',
      verified: false,
      api: {
        endpoint: '/tasks/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Task ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        task: { type: 'object' },
      },
    },
    {
      id: 'get_all_tasks',
      name: 'Get All Tasks',
      description: 'Get all tasks',
      category: 'Task',
      icon: 'list',
      verified: false,
      api: {
        endpoint: '/tasks',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        tasks: { type: 'array' },
      },
    },
    {
      id: 'update_task',
      name: 'Update Task',
      description: 'Update an existing task',
      category: 'Task',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/tasks/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Task ID',
          aiControlled: false,
        },
        name: {
          type: 'string',
          required: false,
          label: 'Task Name',
          aiControlled: true,
          aiDescription: 'Generate a descriptive task name based on the context',
        },
        billableByDefault: {
          type: 'boolean',
          required: false,
          label: 'Billable by Default',
          aiControlled: false,
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          aiControlled: false,
        },
      },
      outputSchema: {
        task: { type: 'object' },
      },
    },
    {
      id: 'delete_task',
      name: 'Delete Task',
      description: 'Delete a task',
      category: 'Task',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/tasks/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Task ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // User Actions
    {
      id: 'get_current_user',
      name: 'Get Current User',
      description: 'Get the currently authenticated user',
      category: 'User',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/users/me',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {},
      outputSchema: {
        user: { type: 'object' },
      },
    },
    {
      id: 'get_user',
      name: 'Get User',
      description: 'Get a specific user',
      category: 'User',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/users/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'User ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        user: { type: 'object' },
      },
    },
    {
      id: 'get_all_users',
      name: 'Get All Users',
      description: 'Get all users',
      category: 'User',
      icon: 'users',
      verified: false,
      api: {
        endpoint: '/users',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        users: { type: 'array' },
      },
    },
    {
      id: 'create_user',
      name: 'Create User',
      description: 'Create a new user',
      category: 'User',
      icon: 'user-plus',
      verified: false,
      api: {
        endpoint: '/users',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          firstName: 'first_name',
          lastName: 'last_name',
          email: 'email',
          telephone: 'telephone',
          timezone: 'timezone',
          hasAccessToAllFutureProjects: 'has_access_to_all_future_projects',
          isContractor: 'is_contractor',
          isAdmin: 'is_admin',
          isProjectManager: 'is_project_manager',
          canSeeRates: 'can_see_rates',
          canCreateProjects: 'can_create_projects',
          canCreateInvoices: 'can_create_invoices',
          isActive: 'is_active',
          weeklyCapacity: 'weekly_capacity',
          defaultHourlyRate: 'default_hourly_rate',
          costRate: 'cost_rate',
        },
      },
      inputSchema: {
        firstName: {
          type: 'string',
          required: true,
          label: 'First Name',
          aiControlled: false,
        },
        lastName: {
          type: 'string',
          required: true,
          label: 'Last Name',
          aiControlled: false,
        },
        email: {
          type: 'string',
          required: true,
          label: 'Email',
          inputType: 'email',
          aiControlled: false,
        },
        telephone: {
          type: 'string',
          required: false,
          label: 'Telephone',
          aiControlled: false,
        },
        timezone: {
          type: 'string',
          required: false,
          label: 'Timezone',
          aiControlled: false,
        },
        hasAccessToAllFutureProjects: {
          type: 'boolean',
          required: false,
          label: 'Has Access to All Future Projects',
          aiControlled: false,
        },
        isContractor: {
          type: 'boolean',
          required: false,
          label: 'Is Contractor',
          aiControlled: false,
        },
        isAdmin: {
          type: 'boolean',
          required: false,
          label: 'Is Admin',
          aiControlled: false,
        },
        isProjectManager: {
          type: 'boolean',
          required: false,
          label: 'Is Project Manager',
          aiControlled: false,
        },
        canSeeRates: {
          type: 'boolean',
          required: false,
          label: 'Can See Rates',
          aiControlled: false,
        },
        canCreateProjects: {
          type: 'boolean',
          required: false,
          label: 'Can Create Projects',
          aiControlled: false,
        },
        canCreateInvoices: {
          type: 'boolean',
          required: false,
          label: 'Can Create Invoices',
          aiControlled: false,
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          default: true,
          aiControlled: false,
        },
        weeklyCapacity: {
          type: 'number',
          required: false,
          label: 'Weekly Capacity (hours)',
          min: 0,
          aiControlled: false,
        },
        defaultHourlyRate: {
          type: 'number',
          required: false,
          label: 'Default Hourly Rate',
          min: 0,
          aiControlled: false,
        },
        costRate: {
          type: 'number',
          required: false,
          label: 'Cost Rate',
          min: 0,
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        first_name: { type: 'string' },
        last_name: { type: 'string' },
        email: { type: 'string' },
      },
    },
    {
      id: 'update_user',
      name: 'Update User',
      description: 'Update an existing user',
      category: 'User',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/users/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'User ID',
          aiControlled: false,
        },
        firstName: {
          type: 'string',
          required: false,
          label: 'First Name',
          aiControlled: false,
        },
        lastName: {
          type: 'string',
          required: false,
          label: 'Last Name',
          aiControlled: false,
        },
        email: {
          type: 'string',
          required: false,
          label: 'Email',
          inputType: 'email',
          aiControlled: false,
        },
        isActive: {
          type: 'boolean',
          required: false,
          label: 'Is Active',
          aiControlled: false,
        },
      },
      outputSchema: {
        user: { type: 'object' },
      },
    },
    {
      id: 'delete_user',
      name: 'Delete User',
      description: 'Delete a user',
      category: 'User',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/users/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'User ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Contact Actions
    {
      id: 'create_contact',
      name: 'Create Contact',
      description: 'Create a new contact',
      category: 'Contact',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/contacts',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          clientId: 'client_id',
          firstName: 'first_name',
          lastName: 'last_name',
          title: 'title',
          email: 'email',
          phoneOffice: 'phone_office',
          phoneMobile: 'phone_mobile',
          fax: 'fax',
        },
      },
      inputSchema: {
        clientId: {
          type: 'string',
          required: true,
          label: 'Client ID',
          aiControlled: false,
        },
        firstName: {
          type: 'string',
          required: true,
          label: 'First Name',
          aiControlled: false,
        },
        lastName: {
          type: 'string',
          required: false,
          label: 'Last Name',
          aiControlled: false,
        },
        title: {
          type: 'string',
          required: false,
          label: 'Title',
          aiControlled: false,
        },
        email: {
          type: 'string',
          required: false,
          label: 'Email',
          inputType: 'email',
          aiControlled: false,
        },
        phoneOffice: {
          type: 'string',
          required: false,
          label: 'Phone Office',
          aiControlled: false,
        },
        phoneMobile: {
          type: 'string',
          required: false,
          label: 'Phone Mobile',
          aiControlled: false,
        },
        fax: {
          type: 'string',
          required: false,
          label: 'Fax',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        first_name: { type: 'string' },
        last_name: { type: 'string' },
        client: { type: 'object' },
      },
    },
    {
      id: 'get_contact',
      name: 'Get Contact',
      description: 'Get a specific contact',
      category: 'Contact',
      icon: 'user',
      verified: false,
      api: {
        endpoint: '/contacts/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Contact ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        contact: { type: 'object' },
      },
    },
    {
      id: 'get_all_contacts',
      name: 'Get All Contacts',
      description: 'Get all contacts',
      category: 'Contact',
      icon: 'users',
      verified: false,
      api: {
        endpoint: '/contacts',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        clientId: {
          type: 'string',
          required: false,
          label: 'Client ID',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        contacts: { type: 'array' },
      },
    },
    {
      id: 'update_contact',
      name: 'Update Contact',
      description: 'Update an existing contact',
      category: 'Contact',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/contacts/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Contact ID',
          aiControlled: false,
        },
        firstName: {
          type: 'string',
          required: false,
          label: 'First Name',
          aiControlled: false,
        },
        lastName: {
          type: 'string',
          required: false,
          label: 'Last Name',
          aiControlled: false,
        },
        email: {
          type: 'string',
          required: false,
          label: 'Email',
          inputType: 'email',
          aiControlled: false,
        },
      },
      outputSchema: {
        contact: { type: 'object' },
      },
    },
    {
      id: 'delete_contact',
      name: 'Delete Contact',
      description: 'Delete a contact',
      category: 'Contact',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/contacts/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Contact ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Invoice Actions
    {
      id: 'create_invoice',
      name: 'Create Invoice',
      description: 'Create a new invoice',
      category: 'Invoice',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/invoices',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          clientId: 'client_id',
          retroInvoiceId: 'retro_invoice_id',
          estimateId: 'estimate_id',
          number: 'number',
          purchaseOrder: 'purchase_order',
          tax: 'tax',
          tax2: 'tax2',
          discount: 'discount',
          subject: 'subject',
          notes: 'notes',
          currency: 'currency',
          issueDate: 'issue_date',
          dueDate: 'due_date',
          paymentTerm: 'payment_term',
        },
      },
      inputSchema: {
        clientId: {
          type: 'string',
          required: true,
          label: 'Client ID',
          aiControlled: false,
        },
        retroInvoiceId: {
          type: 'string',
          required: false,
          label: 'Retainer Invoice ID',
          aiControlled: false,
        },
        estimateId: {
          type: 'string',
          required: false,
          label: 'Estimate ID',
          aiControlled: false,
        },
        number: {
          type: 'string',
          required: false,
          label: 'Invoice Number',
          aiControlled: false,
        },
        purchaseOrder: {
          type: 'string',
          required: false,
          label: 'Purchase Order',
          aiControlled: false,
        },
        tax: {
          type: 'number',
          required: false,
          label: 'Tax Percentage',
          min: 0,
          aiControlled: false,
        },
        tax2: {
          type: 'number',
          required: false,
          label: 'Tax 2 Percentage',
          min: 0,
          aiControlled: false,
        },
        discount: {
          type: 'number',
          required: false,
          label: 'Discount Percentage',
          min: 0,
          aiControlled: false,
        },
        subject: {
          type: 'string',
          required: false,
          label: 'Subject',
          aiControlled: true,
          aiDescription: 'Generate a descriptive subject line for the invoice',
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'Generate professional notes for the invoice',
        },
        currency: {
          type: 'string',
          required: false,
          label: 'Currency',
          aiControlled: false,
        },
        issueDate: {
          type: 'string',
          required: false,
          label: 'Issue Date',
          placeholder: '2024-01-09',
          aiControlled: false,
        },
        dueDate: {
          type: 'string',
          required: false,
          label: 'Due Date',
          placeholder: '2024-02-09',
          aiControlled: false,
        },
        paymentTerm: {
          type: 'string',
          required: false,
          label: 'Payment Term',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        client: { type: 'object' },
        number: { type: 'string' },
        amount: { type: 'number' },
      },
    },
    {
      id: 'get_invoice',
      name: 'Get Invoice',
      description: 'Get a specific invoice',
      category: 'Invoice',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/invoices/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Invoice ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        invoice: { type: 'object' },
      },
    },
    {
      id: 'get_all_invoices',
      name: 'Get All Invoices',
      description: 'Get all invoices',
      category: 'Invoice',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/invoices',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        clientId: {
          type: 'string',
          required: false,
          label: 'Client ID',
          aiControlled: false,
        },
        projectId: {
          type: 'string',
          required: false,
          label: 'Project ID',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          aiControlled: false,
        },
        from: {
          type: 'string',
          required: false,
          label: 'From Date',
          aiControlled: false,
        },
        to: {
          type: 'string',
          required: false,
          label: 'To Date',
          aiControlled: false,
        },
        state: {
          type: 'string',
          required: false,
          label: 'State',
          description: 'Filter by invoice state (draft, open, paid, closed)',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        invoices: { type: 'array' },
      },
    },
    {
      id: 'update_invoice',
      name: 'Update Invoice',
      description: 'Update an existing invoice',
      category: 'Invoice',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/invoices/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Invoice ID',
          aiControlled: false,
        },
        subject: {
          type: 'string',
          required: false,
          label: 'Subject',
          aiControlled: true,
          aiDescription: 'Generate a descriptive subject line for the invoice',
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'Generate professional notes for the invoice',
        },
        purchaseOrder: {
          type: 'string',
          required: false,
          label: 'Purchase Order',
          aiControlled: false,
        },
      },
      outputSchema: {
        invoice: { type: 'object' },
      },
    },
    {
      id: 'delete_invoice',
      name: 'Delete Invoice',
      description: 'Delete an invoice',
      category: 'Invoice',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/invoices/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Invoice ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Estimate Actions
    {
      id: 'create_estimate',
      name: 'Create Estimate',
      description: 'Create a new estimate',
      category: 'Estimate',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/estimates',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          clientId: 'client_id',
          number: 'number',
          purchaseOrder: 'purchase_order',
          tax: 'tax',
          tax2: 'tax2',
          discount: 'discount',
          subject: 'subject',
          notes: 'notes',
          currency: 'currency',
          issueDate: 'issue_date',
        },
      },
      inputSchema: {
        clientId: {
          type: 'string',
          required: true,
          label: 'Client ID',
          aiControlled: false,
        },
        number: {
          type: 'string',
          required: false,
          label: 'Estimate Number',
          aiControlled: false,
        },
        purchaseOrder: {
          type: 'string',
          required: false,
          label: 'Purchase Order',
          aiControlled: false,
        },
        tax: {
          type: 'number',
          required: false,
          label: 'Tax Percentage',
          min: 0,
          aiControlled: false,
        },
        tax2: {
          type: 'number',
          required: false,
          label: 'Tax 2 Percentage',
          min: 0,
          aiControlled: false,
        },
        discount: {
          type: 'number',
          required: false,
          label: 'Discount Percentage',
          min: 0,
          aiControlled: false,
        },
        subject: {
          type: 'string',
          required: false,
          label: 'Subject',
          aiControlled: true,
          aiDescription: 'Generate a descriptive subject line for the estimate',
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'Generate professional notes for the estimate',
        },
        currency: {
          type: 'string',
          required: false,
          label: 'Currency',
          aiControlled: false,
        },
        issueDate: {
          type: 'string',
          required: false,
          label: 'Issue Date',
          placeholder: '2024-01-09',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        client: { type: 'object' },
        number: { type: 'string' },
        amount: { type: 'number' },
      },
    },
    {
      id: 'get_estimate',
      name: 'Get Estimate',
      description: 'Get a specific estimate',
      category: 'Estimate',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/estimates/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Estimate ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        estimate: { type: 'object' },
      },
    },
    {
      id: 'get_all_estimates',
      name: 'Get All Estimates',
      description: 'Get all estimates',
      category: 'Estimate',
      icon: 'file-text',
      verified: false,
      api: {
        endpoint: '/estimates',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        clientId: {
          type: 'string',
          required: false,
          label: 'Client ID',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          aiControlled: false,
        },
        from: {
          type: 'string',
          required: false,
          label: 'From Date',
          aiControlled: false,
        },
        to: {
          type: 'string',
          required: false,
          label: 'To Date',
          aiControlled: false,
        },
        state: {
          type: 'string',
          required: false,
          label: 'State',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        estimates: { type: 'array' },
      },
    },
    {
      id: 'update_estimate',
      name: 'Update Estimate',
      description: 'Update an existing estimate',
      category: 'Estimate',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/estimates/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Estimate ID',
          aiControlled: false,
        },
        subject: {
          type: 'string',
          required: false,
          label: 'Subject',
          aiControlled: true,
          aiDescription: 'Generate a descriptive subject line for the estimate',
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'Generate professional notes for the estimate',
        },
      },
      outputSchema: {
        estimate: { type: 'object' },
      },
    },
    {
      id: 'delete_estimate',
      name: 'Delete Estimate',
      description: 'Delete an estimate',
      category: 'Estimate',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/estimates/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Estimate ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Expense Actions
    {
      id: 'create_expense',
      name: 'Create Expense',
      description: 'Create a new expense',
      category: 'Expense',
      icon: 'dollar-sign',
      verified: false,
      api: {
        endpoint: '/expenses',
        method: 'POST',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
        paramMapping: {
          projectId: 'project_id',
          expenseCategoryId: 'expense_category_id',
          spentDate: 'spent_date',
          userId: 'user_id',
          units: 'units',
          totalCost: 'total_cost',
          notes: 'notes',
          billable: 'billable',
        },
      },
      inputSchema: {
        projectId: {
          type: 'string',
          required: true,
          label: 'Project ID',
          aiControlled: false,
        },
        expenseCategoryId: {
          type: 'string',
          required: true,
          label: 'Expense Category ID',
          aiControlled: false,
        },
        spentDate: {
          type: 'string',
          required: true,
          label: 'Spent Date',
          placeholder: '2024-01-09',
          aiControlled: false,
        },
        userId: {
          type: 'string',
          required: false,
          label: 'User ID',
          aiControlled: false,
        },
        units: {
          type: 'number',
          required: false,
          label: 'Units',
          min: 0,
          aiControlled: false,
        },
        totalCost: {
          type: 'number',
          required: false,
          label: 'Total Cost',
          min: 0,
          aiControlled: false,
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'Generate descriptive notes about the expense',
        },
        billable: {
          type: 'boolean',
          required: false,
          label: 'Billable',
          aiControlled: false,
        },
      },
      outputSchema: {
        id: { type: 'string' },
        project: { type: 'object' },
        expense_category: { type: 'object' },
        total_cost: { type: 'number' },
      },
    },
    {
      id: 'get_expense',
      name: 'Get Expense',
      description: 'Get a specific expense',
      category: 'Expense',
      icon: 'dollar-sign',
      verified: false,
      api: {
        endpoint: '/expenses/{id}',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Expense ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        expense: { type: 'object' },
      },
    },
    {
      id: 'get_all_expenses',
      name: 'Get All Expenses',
      description: 'Get all expenses',
      category: 'Expense',
      icon: 'dollar-sign',
      verified: false,
      api: {
        endpoint: '/expenses',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        userId: {
          type: 'string',
          required: false,
          label: 'User ID',
          aiControlled: false,
        },
        clientId: {
          type: 'string',
          required: false,
          label: 'Client ID',
          aiControlled: false,
        },
        projectId: {
          type: 'string',
          required: false,
          label: 'Project ID',
          aiControlled: false,
        },
        isBilled: {
          type: 'boolean',
          required: false,
          label: 'Is Billed',
          aiControlled: false,
        },
        updatedSince: {
          type: 'string',
          required: false,
          label: 'Updated Since',
          aiControlled: false,
        },
        from: {
          type: 'string',
          required: false,
          label: 'From Date',
          aiControlled: false,
        },
        to: {
          type: 'string',
          required: false,
          label: 'To Date',
          aiControlled: false,
        },
        page: {
          type: 'number',
          required: false,
          label: 'Page',
          default: 1,
          min: 1,
          aiControlled: false,
        },
        perPage: {
          type: 'number',
          required: false,
          label: 'Per Page',
          default: 100,
          min: 1,
          max: 100,
          aiControlled: false,
        },
      },
      outputSchema: {
        expenses: { type: 'array' },
      },
    },
    {
      id: 'update_expense',
      name: 'Update Expense',
      description: 'Update an existing expense',
      category: 'Expense',
      icon: 'edit',
      verified: false,
      api: {
        endpoint: '/expenses/{id}',
        method: 'PATCH',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Expense ID',
          aiControlled: false,
        },
        projectId: {
          type: 'string',
          required: false,
          label: 'Project ID',
          aiControlled: false,
        },
        expenseCategoryId: {
          type: 'string',
          required: false,
          label: 'Expense Category ID',
          aiControlled: false,
        },
        spentDate: {
          type: 'string',
          required: false,
          label: 'Spent Date',
          aiControlled: false,
        },
        units: {
          type: 'number',
          required: false,
          label: 'Units',
          aiControlled: false,
        },
        totalCost: {
          type: 'number',
          required: false,
          label: 'Total Cost',
          aiControlled: false,
        },
        notes: {
          type: 'string',
          required: false,
          label: 'Notes',
          inputType: 'textarea',
          aiControlled: true,
          aiDescription: 'Generate descriptive notes about the expense',
        },
      },
      outputSchema: {
        expense: { type: 'object' },
      },
    },
    {
      id: 'delete_expense',
      name: 'Delete Expense',
      description: 'Delete an expense',
      category: 'Expense',
      icon: 'trash',
      verified: false,
      api: {
        endpoint: '/expenses/{id}',
        method: 'DELETE',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {
        id: {
          type: 'string',
          required: true,
          label: 'Expense ID',
          aiControlled: false,
        },
      },
      outputSchema: {
        success: { type: 'boolean' },
      },
    },
    // Company Actions
    {
      id: 'get_company',
      name: 'Get Company',
      description: 'Get company information',
      category: 'Company',
      icon: 'briefcase',
      verified: false,
      api: {
        endpoint: '/company',
        method: 'GET',
        baseUrl: 'https://api.harvestapp.com/v2',
        headers: {
          'Authorization': 'Bearer {accessToken}',
          'Harvest-Account-Id': '{accountId}',
          'User-Agent': 'Fluxturn App',
        },
      },
      inputSchema: {},
      outputSchema: {
        company: { type: 'object', description: 'Company information' },
      },
    },
  ],

  supported_triggers: [],
};
